myfinance-web-netcore/Models/ErrorViewModel.cs
namespace myfinance_web_netcore.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

myfinance-web-netcore/Models/PlanoContaModel.cs
using myfinance_web_netcore.Infra;

namespace myfinance_web_netcore.Models
{
    public class PlanoContaModel
    {
        public int? Id { get; set; }
        public string? Descricao { get; set; }
        public string? Tipo { get; set; }
    }
}

myfinance-web-netcore/Models/TransacaoModel.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace myfinance_web_netcore.Models
{
    public class TransacaoModel
    {
        public int? Id { get; set; }
        public DateTime Data { get; set; }
        public decimal Valor { get; set; }
        public string? Historico { get; set; }
        public string? Tipo { get; set; }

        [Display(Name = "Plano de Contas")]
        public int? IdPlanoConta { get; set; }
        public IEnumerable<SelectListItem> PlanoContas { get; set; }
    }
}

myfinance-web-netcore/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using myfinance_web_netcore.Models;

namespace myfinance_web_netcore.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

myfinance-web-netcore/Controllers/PlanoContaController.cs
using Microsoft.AspNetCore.Mvc;
using myfinance_web_netcore.Domain;
using myfinance_web_netcore.Models;

namespace myfinance_web_netcore.Controllers
{
    public class PlanoContaController : Controller
    {
        private readonly ILogger<PlanoContaController> _logger;

        public PlanoContaController(ILogger<PlanoContaController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            var planoContas = new PlanoConta();
            ViewBag.list = planoContas.ListaPlanoContas();
            return View();
        }

        [HttpGet]
        public IActionResult CriarPlanoConta(int? id)
        {
            if (id != null)
            {
                var planoConta = new PlanoConta().CarregarPlanoContaPorId(id);
                ViewBag.PlanoConta = planoConta;
            }

            return View();
        }

        [HttpPost]
        public IActionResult CriarPlanoConta(PlanoContaModel formulario)
        {
            var planoConta = new PlanoConta();

            if (formulario.Id == null) planoConta.Insert(formulario);
            else planoConta.Atualizar(formulario);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult ExcluirPlanoConta(int id)
        {
            new PlanoConta().Excluir(id);
            return RedirectToAction("Index");
        }
    }
}

myfinance-web-netcore/Controllers/RelatorioPeriodoController.cs
using Microsoft.AspNetCore.Mvc;
using myfinance_web_netcore.Domain;
using myfinance_web_netcore.Models;

namespace myfinance_web_netcore.Controllers
{
    public class RelatorioPeriodoController : Controller
    {
        private readonly ILogger<RelatorioPeriodoController> _logger;

        public RelatorioPeriodoController(ILogger<RelatorioPeriodoController> logger)
        {
            _logger = logger;
        }

        [HttpGet]
        public IActionResult Index(string DataInicio = "1/1/0001", string DataFim = "1/31/0001")
        {
            var relatorio = new RelatorioPeriodo();
            ViewBag.List = relatorio.ListaRelatorios(DataInicio, DataFim);

            return View();
        }

        [HttpGet]
        public IActionResult GerarRelatorio()
        {
            var teste = new RelatorioPeriodo();


            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

myfinance-web-netcore/Controllers/TransacaoController.cs
using Microsoft.AspNetCore.Mvc;
using myfinance_web_netcore.Domain;
using myfinance_web_netcore.Models;

namespace myfinance_web_netcore.Controllers
{
    public class TransacaoController : Controller
    {
        private readonly ILogger<TransacaoController> _logger;

        public TransacaoController(ILogger<TransacaoController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            var transacao = new Transacao();
            ViewBag.List = transacao.ListaTransacoes();
            return View();
        }

        [HttpGet]
        public IActionResult CriarTransacao(int? id)
        {
            var model = new TransacaoModel();
            if (id != null)
            {
                var transacao = new Transacao().CarregarTransacaoPorId(id);
                model = transacao;
            }

            model.PlanoContas = new PlanoConta().ListaSelectItemPlanoContas();
            return View(model);
        }
        [HttpPost]
        public IActionResult CriarTransacao(TransacaoModel formulario)
        {
            var transacao = new Transacao();

            if (formulario.Id == null) transacao.Inserir(formulario);
            else transacao.Atualizar(formulario);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult ExcluirTransacao(int id)
        {
            new Transacao().Excluir(id);
            return RedirectToAction("Index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

myfinance-web-netcore/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "My Finance Web";
}

<div class="text-center">

    <h1 class="display-4">@ViewData["Title"]</h1>

    <h4>Pós-Graduação em Engenharia de Software da PUC-MG</h4>

    <h5>Práticas de Implementação e Evolução de Software</h5>
    <br>

</div>

<div class="row align-items-start">
    <div class="col mt-5 mb-5">
        <p>Como parte prática da disciplina, construímos um sistema para controle de finanças pessoais bem simples,
            que
            permite
            ao usuário registrar planos de contas e transações realizadas para consulta posterior.</p>
    </div>
    <div class="col mt-5 mb-5">
        <p>O sistema foi arquitetado no padrão MVC, utilizando a linguagem ASP.NET CORE MVC na versão .NET 6.0 com
            Banco de
            Dados SQL-SERVER.</p>
    </div>
</div>


<div class="text-center">
    <p>Mais detalhes podem ser encontrados no repositório do <a
            href="https://github.com/bernardobt/my-finance-web-netcore">GitHub</a>.
    </p>
</div>

myfinance-web-netcore/Views/PlanoConta/CriarPlanoConta.cshtml
@model PlanoContaModel
@{
    ViewData["Title"] = "Plano de Contas";

    var vDescricao = string.Empty;
    var vTipo = string.Empty;

    try
    {
        vDescricao = @ViewBag.PlanoConta.Descricao;
        vTipo = @ViewBag.PlanoConta.Tipo;
    }
    catch { }
}

<h1>@ViewData["Title"] </h1>

<form asp-controller="PlanoConta" asp-action="CriarPlanoConta">
    <input type="hidden" asp-for="Id">

    <div class="mt-3 mb-3">
        <label for="fname">Descrição:</label><br>
        <input type="text" class="form-control" asp-for="Descricao" value=@vDescricao required>
    </div>

    <div class="mb-3">
        <label for="fname">Tipo:</label><br>
        <input type="text" class="form-control" asp-for="Tipo" value=@vTipo required>
    </div>

    <div>
        <button type="submit" class="btn btn-primary text-capitalize mb-3">Registrar</button>
        <button type="button" class="btn btn-secondary text-capitalize mb-3" onclick="Cancelar()">Cancelar</button>
    </div>

</form>

<script>
    function Cancelar() {
        window.location.href = "../"
    }
</script>

myfinance-web-netcore/Views/PlanoConta/Index.cshtml
@{
    ViewData["Title"] = "Plano Contas";
}

<h3>Plano de Contas <button type="button" class="btn btn-block btn-primary float-end" onclick="CriarPlanoConta()">Criar
        Plano de Contas</button></h3>
<hr>

<table class='table table-striped table-hover table-sm'>
    <tr>
        <th>Id</th>
        <th>Descrição</th>
        <th>Tipo</th>
        <th></th>
    </tr>

    @{
        foreach (var item in (List<PlanoContaModel>)ViewBag.list)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Descricao</td>
                <td>@item.Tipo</td>
                <td>
                    <div class="btn-group btn-group-sm float-end" role="group">
                        <button class='btn btn-secondary text-capitalize' onclick="EditarPlanoConta(@item.Id)">editar</button>
                        <button class='btn btn-danger text-capitalize' onclick="ExcluirPlanoConta(@item.Id)">deletar</button>
                    </div>
                </td>
            </tr>
        }
    }

</table>

<script>
    function CriarPlanoConta() {
        window.location.href = "../PlanoConta/CriarPlanoConta";
    }
    function EditarPlanoConta(id) {
        window.location.href = "../PlanoConta/CriarPlanoConta/" + id;
    }
    function ExcluirPlanoConta(id) {
        window.location.href = "../PlanoConta/ExcluirPlanoConta/" + id;
    }
</script>

myfinance-web-netcore/Views/RelatorioPeriodo/Index.cshtml
@{
    ViewData["Title"] = "Relatório de Transações Por Período";
}


<h3>@ViewData["Title"]</h3>
<hr>

<form asp-controller="RelatorioPeriodo" asp-action="Index" method="get">
    <div class="row mt-3 input-group">

        <div class="col">
            <label>Início:</label>
            <input id="inicio" type="date" name="DataInicio" class="form-control" required>
        </div>

        <div class="col">
            <label>Fim:</label>
            <input id="fim" type="date" name="DataFim" class="form-control" required>
        </div>
        <div class="col align-self-end">
            <button type="submit" class="btn btn-block btn-primary float-end">Filtrar</button>
        </div>
    </div>

</form>
<hr>

<figure class="figure">
    <canvas id="myChart" width="400" height="400"></canvas>
</figure>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<script>const ctx = document.getElementById('myChart').getContext('2d');
    if (@ViewBag.list[0] > 0 || @ViewBag.list[1] > 0) {
        const myChart = new Chart(
            ctx,
            {
                type: 'pie',
                data: {
                    labels: ['Despesas', 'Receitas'],
                    datasets: [{
                        label: '# of Votes', data: [@ViewBag.list[0], @ViewBag.list[1]],
                        backgroundColor: ['rgba(255, 99, 132, 0.6)', 'rgba(99, 255, 132, 0.6)'],
                        borderColor: ['rgba(255, 99, 132, 1)', 'rgba(80, 255, 100, 1)'],
                        borderWidth: 3
                    }]
                },
                options: {
                    plugins: {
                        title: {
                            display: true,
                            text: 'Receita e Despesa por período',
                            padding: {
                                top: 1,
                                bottom: 15
                            }
                        },
                        legend: {
                            position: 'bottom',
                            align: "center",
                            title: {
                                display: true,
                                text: 'Legenda',
                                padding: {
                                    top: 30
                                }
                            }
                        },
                        chartAreaBorder: {
                            borderColor: 'red',
                            borderWidth: 2,
                            borderDash: [5, 5],
                            borderDashOffset: 2,
                        }
                    }
                }
            });
    }
</script>

myfinance-web-netcore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - myfinance_web_netcore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/myfinance_web_netcore.styles.css" asp-append-version="true" />
</head>

<body class="d-flex flex-column min-vh-100 mb-0">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">My Finance Web Netcore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Transacao"
                                asp-action="Index">Transações</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="PlanoConta"
                                asp-action="Index">Planos Conta</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="RelatorioPeriodo"
                                asp-action="Index">Relatório Período</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home"
                                asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted mt-auto bg-light p-1">
        <div class="container">
            &copy; 2022 - myfinance_web_netcore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

myfinance-web-netcore/Views/Transacao/CriarTransacao.cshtml
@using System.Globalization
@model TransacaoModel

@{
    ViewData["Title"] = "Registro de Transação Financeira";

    var vData = "";
    var vDescricao = "";
    var vTipo = "";
    var vValor = "";
    var vId = 0;
    var vPlanoContaId = 0;

    try
    {
        vId = int.Parse(@ViewBag.Registro.Id.ToString());
        vData = DateTime.Parse(@ViewBag.Registro.Data.ToString()).ToString("yyyy-MM-dd");
        vPlanoContaId = int.Parse(@ViewBag.Registro.IdPlanoConta.ToString());
        vDescricao = @ViewBag.Registro.Historico.ToString();
        vTipo = @ViewBag.Registro.Tipo.ToString();

        CultureInfo invC = CultureInfo.InvariantCulture;
        string value;
        value = @ViewBag.Registro.Valor.ToString(invC);
        vValor = value;
    }
    catch { }
}

<h1>@ViewData["Title"]</h1>

<form asp-controller="Transacao" asp-action="CriarTransacao">
    <input type="hidden" asp-for="Id">

    <div class="form-group mb-3">
        <lable>Data:</lable>
        <input type="date" asp-for="Data" value="@vData" class="form-control">
        <span asp-validation-for="Data" class="text-danger"></span>
    </div>

    <div class="form-group mb-3">
        <lable>Tipo</lable>
        <input type="text" asp-for="Tipo" class="form-control" value="@vTipo">
        <span asp-validation-for="Data" class="text-danger"></span>
    </div>

    <div class="form-group mb-3">
        <lable>Valor</lable>
        <input type="text" asp-for="Valor" value="@vValor" step="0.01" class="form-control">
        <span asp-validation-for="Valor" class="text-danger"></span>
    </div>

    <div class="form-group mb-3">
        <lable>Histórico</lable>
        @Html.TextArea("Historico", vDescricao, new { @class = "form-control" })
        <span asp-validation-for="Historico" class="text-danger"></span>
    </div>

    <div class="form-group mb-3">
        @Html.LabelFor(x => Model.IdPlanoConta)
        @Html.DropDownListFor(x => Model.IdPlanoConta,
        new SelectList(Model.PlanoContas, "Value", "Text"),
        new{ @class = "form-select", id = "IdPlanoConta" }
        )
    </div>

    <div>
        <button type="submit" class="btn btn-block btn-primary mb-3">Registrar</button>
        <button type="button" class="btn btn-block btn-secondary mb-3" onclick="Cancelar()">Cancelar</button>
    </div>

</form>

<script>
    function Cancelar() {
        window.location.href = "../";
    }
</script>

myfinance-web-netcore/Views/Transacao/Index.cshtml
@{
    ViewData["Title"] = "Transações";
}

<h3>Transações Financeiras <button type="button" class="btn btn-block btn-primary float-end"
        onclick="CriarTransacao()">Nova Transação</button></h3>
<hr>

<table class='table table-striped table-hover table-sm'>
    <tr>
        <th>Id</th>
        <th>Data</th>
        <th>Valor</th>
        <th>Tipo</th>
        <th>Histórico</th>
        <th>Plano de Conta</th>
        <th></th>
    </tr>

    @{
        foreach (var item in (List<TransacaoModel>)ViewBag.list)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Data</td>
                <td>@item.Valor</td>
                <td>@item.Tipo</td>
                <td>@item.Historico</td>
                <td>@item.IdPlanoConta</td>
                <td>
                    <div class="btn-group btn-group-sm float-end" role="group">
                        <button class='btn btn-secondary text-capitalize' onclick="EditarTransacao(@item.Id)">editar</button>
                        <button class='btn btn-danger text-capitalize' onclick="ExcluirTransacao(@item.Id)">deletar</button>
                    </div>
                </td>
            </tr>
        }
    }

</table>

<script>
    function CriarTransacao() {
        window.location.href = "../Transacao/CriarTransacao";
    }
    function EditarTransacao(id) {
        window.location.href = "../Transacao/CriarTransacao/" + id;
    }
    function ExcluirTransacao(id) {
        window.location.href = "../Transacao/ExcluirTransacao/" + id;
    }
</script>